language: swift
osx_image: xcode13
env:
- DESTINATION="OS=15.0,name=iPhone 12" SCHEME="XLProductName" SDK=iphonesimulator15.0

script:
- xcodebuild -workspace shabbat-helper.xcworkspace -scheme shabbat-helper -configuration "ProdAdHoc" -sdk iphonesimulator15.0

